# Generated by Django 3.0.4 on 2021-03-04 16:04

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20210302_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='Images',
            field=models.ImageField(upload_to='picdata/%y', validators=[uploader.models.validate_image]),
        ),
    ]
