# Generated by Django 3.0.4 on 2021-03-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=0)),
                ('Images', models.ImageField(default='', upload_to='profiledata/images')),
                ('Skills', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
