# Generated by Django 3.0.4 on 2021-03-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('skill_id', models.IntegerField(default=0)),
            ],
        ),
    ]
